BibleVerseApplication/BibleVerseApplication/Controllers/SearchVerseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BibleVerseApplication.Models;

namespace BibleVerseApplication.Controllers
{
    [Authorize]
    public class SearchVerseController : Controller
    {
        private BibleVerseApplicationContext db = new BibleVerseApplicationContext();

        // GET: SearchVerse
        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy == "Testament")
            {
                return View(db.BibleUserEntries.Where(x => x.TestamentSelection == search || search == null).ToList());
            }
            else
            {
                return View(db.BibleUserEntries.Where(x => x.BookSelection.StartsWith(search) || search == null).ToList());
            }
            
        }
        // GET: SearchVerse/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BibleUserEntry bibleUserEntry = db.BibleUserEntries.Find(id);
            if (bibleUserEntry == null)
            {
                return HttpNotFound();
            }
            return View(bibleUserEntry);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BibleVerseApplication/BibleVerseApplication/Views/SearchVerse/Details.cshtml
@model BibleVerseApplication.Models.BibleUserEntry

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>BibleUserEntry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TestamentSelection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestamentSelection)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookSelection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookSelection)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChapterNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChapterNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseText)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BibleVerseApplication/BibleVerseApplication/Views/SearchVerse/Index.cshtml
@model IEnumerable<BibleVerseApplication.Models.BibleUserEntry>

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome to your favorite Bible Verse Search Page</h2>
<h4>Please Select the Search Criteria to begin your search</h4>
<div style="font-family: sans-serif">
    <p>
    @using (Html.BeginForm("Index", "SearchVerse", FormMethod.Get))
    {
        <b>Search By:</b>
        <b>@Html.RadioButton("SearchBy", "Testament") <text>Testament</text></b>
        <b>@Html.RadioButton("SearchBy", "BookName", true ) <text>Book Name</text></b>
        @Html.TextBox("Search") <input type="submit" value="Search"/>
    }
    </p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TestamentSelection)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookSelection)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChapterNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VerseNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VerseText)
            </th>
            <th></th>
        </tr>
        @if (!Model.Any())
        {
            <tr>
                <td colspan="5">No Data Matches your Search Criteria</td>
            </tr>

        }
        else
        {


            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TestamentSelection)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookSelection)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ChapterNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VerseNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VerseText)
                    </td>                   
                </tr>
            }
        }

    </table>
    <p>
        @Html.ActionLink("Back to Search Records", "Index")
    </p>
</div>